# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MA35D1)    += ma35d1-iot-128m.dtb \
				ma35d1-iot-256m.dtb \
				ma35d1-iot-512m.dtb \
				ma35d1-som-256m.dtb \
				ma35d1-som-512m.dtb \
				ma35d1-som-1g.dtb \
				ma35d1-som-2g.dtb

dtb-$(CONFIG_ARCH_MA35DZ)    += ma35dz-iot-256m.dts

dtb-$(CONFIG_ARCH_MA35HZ)    += ma35hz-iot-128m.dts

always          := $(dtb-y)
clean-files     := *.dtb

