#
# Makefile for mmp specific clk
#
obj-$(CONFIG_ARCH_MA35D1) += clk-ma35d1.o clkdivider-ma35d1.o clk-ma35d1-pll.o
obj-$(CONFIG_ARCH_MA35DZ) += clk-ma35dz.o clkdivider-ma35dz.o clk-ma35dz-pll.o
obj-$(CONFIG_ARCH_MA35HZ) += clk-ma35hz.o clkdivider-ma35hz.o clk-ma35hz-pll.o



