# SPDX-License-Identifier: GPL-2.0-only
obj-y += nuvoton-crypto.o
obj-$(CONFIG_CRYPTO_ECDH) += nuvoton-ecc.o
obj-$(CONFIG_CRYPTO_RSA) += nuvoton-rsa.o
nuvoton-crypto-objs:= nuvoton-crypto.o nuvoton-prng.o nuvoton-aes.o nuvoton-sha.o
